"""
The Google Fonts library: a committed catalogue, and bytes fetched on demand.

Vendoring all of Google Fonts is not an option: the 1832 usable families come to
857MB. So the *index* ships with the app (app/data/google_fonts.json, 416KB,
generated by scripts/build_font_catalogue.py) and a family's actual TTF is
downloaded the first time anyone selects it, then cached forever.

The guarantee that matters is unchanged: **one file, read by both renderers.**
The download lands in a directory shared by the backend and the worker, libass
loads it from there, and the browser is served the identical bytes from
`/api/fonts/{key}/{weight}.ttf`. There is no metric-compatibility argument to
make, because there is only ever one file.

The server does the fetching, not the visitor's browser. That is deliberate on
an app whose claim is that nothing leaves your machine: no viewer's IP is ever
handed to Google, and a caption font cannot be used to track anyone. It also
means an offline box keeps working with whatever is already cached.

Variable fonts are the interesting case, and they used to be simply excluded —
which cost the library Roboto, Inter, Open Sans and most of the popular list,
because Google publishes those as variable only. Handing one to both renderers
genuinely does not work: libass takes the default instance and synthesises a
fake bold while the browser interpolates a real one along the weight axis.

They are included now as *source*. `_instance` pins every axis and writes a
real static face, so what lands in the cache is an ordinary TTF and the
one-file property holds exactly as it does for the families Google ships
static. What is never allowed is a variable file reaching either renderer, and
`_validate` enforces that on the bytes rather than trusting the pipeline.
"""

from __future__ import annotations

import io
import json
import logging
import struct
import threading
import urllib.error
import urllib.request
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

from app.config import get_settings

log = logging.getLogger(__name__)

CATALOGUE_PATH = Path(__file__).resolve().parent.parent / "data" / "google_fonts.json"

# Long enough for a 6MB font on a slow line, short enough that a hung CDN does
# not hold a request open until the client gives up.
DOWNLOAD_TIMEOUT = 60

# One lock per process is enough. Two requests for the same uncached family
# arrive together often — the picker previews a font the moment it is
# highlighted — and without this they would both download and then race to
# write the same path.
_download_lock = threading.Lock()


@dataclass(frozen=True)
class LibraryFont:
    key: str
    family: str
    category: str
    regular: str
    bold: str | None
    bytes: int
    #: Axis tags to their default values, for a family Google ships only as a
    #: variable font. None means the paths above are already static files.
    axes: tuple[tuple[str, float], ...] | None = None

    @property
    def has_bold(self) -> bool:
        return self.bold is not None

    @property
    def is_variable(self) -> bool:
        return self.axes is not None


#: Counts recorded by the generator, so the picker can say what is missing
#: without hardcoding numbers that go stale on the next catalogue rebuild.
_EMPTY_META = {
    "google_families": 0,
    "static": 0,
    "instanced": 0,
    "skipped_oversized": 0,
    "skipped_unusable": 0,
}


@lru_cache(maxsize=1)
def _catalogue() -> tuple[str, dict[str, LibraryFont], dict[str, int]]:
    """Parsed once per process; the file is static and 416KB of JSON."""
    if not CATALOGUE_PATH.exists():
        log.warning("font catalogue missing at %s; the library will be empty", CATALOGUE_PATH)
        return "", {}, dict(_EMPTY_META)

    payload = json.loads(CATALOGUE_PATH.read_text(encoding="utf-8"))
    fonts = {
        entry["key"]: LibraryFont(
            key=entry["key"],
            family=entry["family"],
            category=entry["category"],
            regular=entry["regular"],
            bold=entry["bold"],
            bytes=entry["bytes"],
            # A tuple, not the dict, so LibraryFont stays hashable and frozen.
            axes=tuple(entry["axes"].items()) if entry.get("axes") else None,
        )
        for entry in payload["fonts"]
    }
    return payload["base_url"], fonts, {**_EMPTY_META, **payload.get("meta", {})}


def all_fonts() -> dict[str, LibraryFont]:
    return _catalogue()[1]


def catalogue_meta() -> dict[str, int]:
    """What the generator kept and skipped, for the picker's info panel."""
    return _catalogue()[2]


def get(key: str) -> LibraryFont | None:
    return _catalogue()[1].get(key)


def matches(query: str, *, category: str | None = None) -> list[LibraryFont]:
    """
    Every family matching a query, prefix matches first.

    Substring, not fuzzy. With 1301 families a user types the first few letters
    of a name they already have in mind, and a fuzzy matcher mostly adds
    surprises.
    """
    fonts = list(_catalogue()[1].values())
    if category:
        fonts = [f for f in fonts if f.category == category]

    needle = query.strip().lower()
    if not needle:
        return fonts

    starts = [f for f in fonts if f.family.lower().startswith(needle)]
    contains = [
        f
        for f in fonts
        if needle in f.family.lower() and not f.family.lower().startswith(needle)
    ]
    return starts + contains


def search(query: str, *, category: str | None = None, limit: int = 60) -> list[LibraryFont]:
    """The first `limit` matches — what a picker actually renders."""
    return matches(query, category=category)[:limit]


# ── The cache on disk ────────────────────────────────────────────────────


#: Metric sidecars go in a subdirectory, not beside the fonts.
#:
#: libass is handed this directory as `fontsdir` and opens *every* file in it,
#: so a .json sitting next to the .ttf produced "Error opening memory font
#: roboto-regular.json" on every single burn — one line per cached family,
#: which would grow to hundreds and is exactly the kind of noise a real error
#: hides in. libass reads the directory without recursing, so a subdirectory is
#: invisible to it.
METRICS_DIR = "metrics"

_migrated = False


def cache_dir() -> Path:
    path = Path(get_settings().font_cache_dir)
    path.mkdir(parents=True, exist_ok=True)
    (path / METRICS_DIR).mkdir(exist_ok=True)

    # One-time tidy-up of sidecars written by an earlier version straight into
    # the font directory. Moved rather than deleted: the win span in them was
    # measured at download time and is not recoverable from a file already
    # cached, since nothing will fetch it again.
    global _migrated
    if not _migrated:
        _migrated = True
        for stale in path.glob("*.json"):
            stale.replace(path / METRICS_DIR / stale.name)

    return path


def cached_path(key: str, weight: str) -> Path:
    """
    Where a downloaded face lives.

    `key` is a catalogue slug — lowercase letters and digits only, produced by
    the generator — and `weight` is checked against a literal below, so neither
    can walk out of this directory.
    """
    return cache_dir() / f"{key}-{weight}.ttf"


def metrics_path(key: str, weight: str) -> Path:
    """
    The sidecar holding what was measured about a face when it was fetched.

    Makes its own directory rather than relying on cache_dir() having done it.
    They are not always the same call — anything that overrides where the cache
    lives gets the subdirectory for free this way, which is how the first
    version of this broke.
    """
    directory = cache_dir() / METRICS_DIR
    directory.mkdir(parents=True, exist_ok=True)
    return directory / f"{key}-{weight}.json"


def _validate(data: bytes) -> float:
    """
    Confirm the download is a static TrueType face, and return its win span.

    Raises ValueError otherwise. Worth doing rather than trusting the URL: a
    404 page written to disk as `Anton-Regular.ttf` would make libass fall back
    silently, which is the failure mode this whole area is built to avoid.

    The span returned is (usWinAscent + usWinDescent) / unitsPerEm. libass sizes
    a font so that span equals the requested Fontsize, while CSS `font-size`
    means the em square, so the browser has to divide by it to draw text the
    size the export will use.
    """
    if data[:4] not in (b"\x00\x01\x00\x00", b"true", b"ttcf"):
        raise ValueError(f"not a TrueType file (magic {data[:4]!r})")

    count = struct.unpack(">H", data[4:6])[0]
    tables: dict[str, int] = {}
    for i in range(count):
        off = 12 + i * 16
        if off + 16 > len(data):
            raise ValueError("truncated table directory")
        tables[data[off : off + 4].decode("latin-1", "replace")] = struct.unpack(
            ">II", data[off + 8 : off + 16]
        )[0]

    if "fvar" in tables:
        raise ValueError("variable font; the catalogue should have excluded this")
    for required in ("head", "OS/2", "glyf"):
        if required not in tables:
            raise ValueError(f"missing {required} table")

    upem = struct.unpack(">H", data[tables["head"] + 18 : tables["head"] + 20])[0]
    ascent, descent = struct.unpack(">HH", data[tables["OS/2"] + 74 : tables["OS/2"] + 78])
    if not upem or not (ascent + descent):
        raise ValueError("font declares no usable vertical metrics")
    return (ascent + descent) / upem


#: The two weights a caption style can ask for, and what to pin `wght` to.
_WEIGHTS = {"regular": 400, "bold": 700}


def _instance(data: bytes, font: LibraryFont, weight: str) -> bytes:
    """
    Pin a variable font's axes and return a genuine static face.

    This is what makes Google's most popular families usable at all. They are
    published as variable fonts only, and handing one to both renderers does
    not work: libass takes the default instance and synthesises a fake bold,
    while the browser interpolates a real one along the weight axis. Same file,
    two different letters.

    Every axis is pinned — `wght` to the requested weight, everything else to
    the default recorded in the catalogue — because an axis left free leaves
    `fvar` in the output, and a font with `fvar` is exactly the thing that
    cannot be shared between the two renderers.

    Imported here rather than at module scope: fontTools is a heavy import and
    a deployment that never touches a variable family should not pay for it.
    """
    from fontTools.ttLib import TTFont
    from fontTools.varLib import instancer

    pins = {tag: default for tag, default in font.axes or ()}
    if "wght" in pins:
        pins["wght"] = _WEIGHTS[weight]

    parsed = TTFont(io.BytesIO(data))
    # updateFontNames, or the face keeps the variable family's naming and
    # fontconfig hands libass something the browser was never asked for.
    instancer.instantiateVariableFont(parsed, pins, inplace=True, updateFontNames=True)

    out = io.BytesIO()
    parsed.save(out)
    return out.getvalue()


def ensure(key: str, weight: str = "regular") -> Path:
    """
    The path to a face on disk, downloading it if this is the first request.

    Raises LookupError for an unknown key or a bold that does not exist, and
    RuntimeError if the download fails.
    """
    if weight not in _WEIGHTS:
        raise LookupError(f"unknown weight: {weight}")

    font = get(key)
    if font is None:
        raise LookupError(f"unknown font: {key}")

    remote = font.regular if weight == "regular" else font.bold
    if remote is None:
        raise LookupError(f"{font.family} has no bold face")

    path = cached_path(key, weight)
    if path.exists() and path.stat().st_size > 0:
        return path

    base_url = _catalogue()[0]
    url = base_url + remote

    with _download_lock:
        # Re-checked inside the lock: another request may have finished while
        # this one waited, and re-downloading would be pure waste.
        if path.exists() and path.stat().st_size > 0:
            return path

        log.info("fetching %s %s from %s", font.family, weight, url)
        try:
            request = urllib.request.Request(
                url, headers={"User-Agent": "VideoCaptionMaker"}
            )
            data = urllib.request.urlopen(request, timeout=DOWNLOAD_TIMEOUT).read()
        except (urllib.error.URLError, TimeoutError) as exc:
            raise RuntimeError(f"could not download {font.family}: {exc}") from exc

        if font.is_variable:
            try:
                data = _instance(data, font, weight)
            except Exception as exc:  # noqa: BLE001 — fontTools raises broadly
                raise RuntimeError(
                    f"could not pin {font.family} to {weight}: {exc}"
                ) from exc

        try:
            # Deliberately still checked after instancing rather than trusting
            # fontTools. The no-fvar assertion is the one that matters: an axis
            # left unpinned would sail through here as a variable font and only
            # show up as a preview that does not match the export.
            span = _validate(data)
        except ValueError as exc:
            raise RuntimeError(f"{font.family} downloaded but is unusable: {exc}") from exc

        # Written beside and moved into place, so a reader in the worker never
        # sees a half-written font — the rename is atomic within a filesystem.
        temporary = path.with_suffix(".part")
        temporary.write_bytes(data)
        temporary.replace(path)

        # Cached rather than recomputed on every render — but in the metrics
        # subdirectory, because libass opens everything in the font directory.
        metrics_path(key, weight).write_text(
            json.dumps({"win_span": span, "bytes": len(data)}), encoding="utf-8"
        )
        log.info("cached %s (%d KB, win span %.4f)", path.name, len(data) // 1024, span)

    return path


def win_span(key: str, weight: str = "regular") -> float | None:
    """The cached vertical span, or None if the face has not been fetched."""
    sidecar = metrics_path(key, weight)
    if not sidecar.exists():
        return None
    try:
        return json.loads(sidecar.read_text(encoding="utf-8"))["win_span"]
    except (json.JSONDecodeError, KeyError):
        return None
