"""
Local filesystem storage for uploaded media.

Every path this module hands out is generated by us, never derived from user
input. A filename like "../../etc/passwd" or a Windows device name is a real
attack, and the defence is not to sanitise the user's string but to refuse to
use it as a path at all: the stored name is a UUID, and the original is kept
in the database purely as a label.

Milestone 3 stores files locally. STORAGE_BACKEND in .env is the seam where
an S3 implementation slots in later.
"""

import shutil
import uuid
from pathlib import Path

from app.config import get_settings

settings = get_settings()

# Extensions we accept, checked alongside the declared content type.
ALLOWED_EXTENSIONS = {".mp4", ".mov", ".mkv", ".webm", ".avi", ".m4v"}

ALLOWED_CONTENT_TYPES = {
    "video/mp4",
    "video/quicktime",
    "video/x-matroska",
    "video/webm",
    "video/x-msvideo",
    "video/x-m4v",
}

# Read/write in 1 MiB chunks so a 2 GB upload never sits in memory.
CHUNK_SIZE = 1024 * 1024


def storage_root() -> Path:
    root = Path(settings.storage_local_path)
    root.mkdir(parents=True, exist_ok=True)
    return root


def _user_dir(user_id: int) -> Path:
    """One directory per user — keeps listings small and deletes simple."""
    path = storage_root() / f"user_{user_id}"
    path.mkdir(parents=True, exist_ok=True)
    return path


def build_storage_path(user_id: int, original_filename: str) -> tuple[Path, str]:
    """
    Return (absolute path to write, path relative to the storage root).

    The filename is a fresh UUID; only the extension is taken from the upload,
    and only after being checked against an allowlist. Two users uploading
    "video.mp4" can never collide, and nothing the user typed reaches the
    filesystem.
    """
    suffix = Path(original_filename).suffix.lower()
    if suffix not in ALLOWED_EXTENSIONS:
        suffix = ".mp4"

    name = f"{uuid.uuid4().hex}{suffix}"
    absolute = _user_dir(user_id) / name
    return absolute, f"user_{user_id}/{name}"


def resolve(relative_path: str) -> Path:
    """
    Turn a stored relative path back into an absolute one, refusing anything
    that escapes the storage root.

    Defence in depth: these values come from our own database rows, but a bug
    or a future feature that lets users influence them shouldn't become a
    filesystem read primitive.
    """
    root = storage_root().resolve()
    candidate = (root / relative_path).resolve()

    # is_relative_to is exact; string prefix comparison would let
    # "/app/storage-evil" pass as being under "/app/storage".
    if not candidate.is_relative_to(root):
        raise ValueError(f"Refusing to access path outside storage root: {relative_path}")

    return candidate


def delete(relative_path: str | None) -> None:
    """Remove a stored file. Missing files are fine — delete is idempotent."""
    if not relative_path:
        return
    try:
        resolve(relative_path).unlink(missing_ok=True)
    except ValueError:
        # Path was outside the root; nothing legitimate to delete.
        pass


def free_space_bytes() -> int:
    return shutil.disk_usage(storage_root()).free
