"""add sessions_valid_from to users

Revision ID: 0bddc3271cec
Revises: 77c7d397c3d0
Create Date: 2026-08-07 14:28:13.018193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bddc3271cec'
down_revision: Union[str, None] = '77c7d397c3d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable with no backfill: NULL means "nothing has been invalidated",
    # so every existing session stays valid. Stamping now() on every row
    # instead would log out the entire user base to deploy a feature none of
    # them asked for.
    op.add_column('users', sa.Column('sessions_valid_from', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessions_valid_from')
    # ### end Alembic commands ###
