"""create videos table

Revision ID: 26f3e4735baf
Revises: 527ac85c21a5
Create Date: 2026-08-06 07:36:47.383462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '26f3e4735baf'
down_revision: Union[str, None] = '527ac85c21a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_path', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='video_status'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_videos_owner_id'), 'videos', ['owner_id'], unique=False)
    op.create_index(op.f('ix_videos_status'), 'videos', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_videos_status'), table_name='videos')
    op.drop_index(op.f('ix_videos_owner_id'), table_name='videos')
    op.drop_table('videos')
    # Autogenerate omits this: in Postgres an ENUM is a standalone type that
    # outlives the table using it, so without the drop a later upgrade fails
    # with "type video_status already exists".
    sa.Enum(name='video_status').drop(op.get_bind(), checkfirst=True)
