"""add caption styles and per-caption overrides

Revision ID: 4ad6619406ad
Revises: bca4d22a7575
Create Date: 2026-08-07 12:12:07.138004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4ad6619406ad'
down_revision: Union[str, None] = 'bca4d22a7575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caption_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('font_key', sa.String(length=32), nullable=False),
    sa.Column('font_size', sa.Integer(), nullable=False),
    sa.Column('bold', sa.Boolean(), nullable=False),
    sa.Column('italic', sa.Boolean(), nullable=False),
    sa.Column('text_color', sa.String(length=7), nullable=False),
    sa.Column('outline_color', sa.String(length=7), nullable=False),
    sa.Column('outline_width', sa.Integer(), nullable=False),
    sa.Column('box_color', sa.String(length=7), nullable=False),
    sa.Column('box_opacity', sa.Float(), nullable=False),
    sa.Column('position', sa.Enum('top', 'middle', 'bottom', name='caption_vertical_position'), nullable=False),
    sa.Column('alignment', sa.Enum('left', 'center', 'right', name='caption_alignment'), nullable=False),
    sa.Column('margin_v', sa.Integer(), nullable=False),
    sa.Column('margin_h', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_caption_styles_video_id'), 'caption_styles', ['video_id'], unique=True)
    op.add_column('captions', sa.Column('override_color', sa.String(length=7), nullable=True))
    op.add_column('captions', sa.Column('override_bold', sa.Boolean(), nullable=True))
    op.add_column('captions', sa.Column('override_scale', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_column('captions', 'override_scale')
    op.drop_column('captions', 'override_bold')
    op.drop_column('captions', 'override_color')
    op.drop_index(op.f('ix_caption_styles_video_id'), table_name='caption_styles')
    op.drop_table('caption_styles')

    # Autogenerate creates these types with the table but never drops them.
    # Postgres ENUMs outlive the table that used them, so without this a
    # downgrade followed by an upgrade fails with "type already exists" —
    # the same trap the videos migration hit with video_status.
    sa.Enum(name='caption_vertical_position').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='caption_alignment').drop(op.get_bind(), checkfirst=True)
