"""add exports table

Revision ID: 77c7d397c3d0
Revises: 4ad6619406ad
Create Date: 2026-08-07 13:07:17.099826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '77c7d397c3d0'
down_revision: Union[str, None] = '4ad6619406ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('format', sa.Enum('srt', 'vtt', 'json', 'mp4', name='export_format'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='export_status'), nullable=False),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('progress', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exports_video_created', 'exports', ['video_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_exports_video_id'), 'exports', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(op.f('ix_exports_video_id'), table_name='exports')
    op.drop_index('ix_exports_video_created', table_name='exports')
    op.drop_table('exports')

    # Autogenerate creates these with the table and never drops them. Postgres
    # ENUMs outlive their table, so a downgrade then upgrade fails with "type
    # already exists" — the third time this has come up in this project.
    sa.Enum(name='export_format').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='export_status').drop(op.get_bind(), checkfirst=True)
