"""add captions and video progress

Revision ID: bca4d22a7575
Revises: 26f3e4735baf
Create Date: 2026-08-06 08:01:14.146419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bca4d22a7575'
down_revision: Union[str, None] = '26f3e4735baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captions_video_id'), 'captions', ['video_id'], unique=False)
    op.create_index('ix_captions_video_sequence', 'captions', ['video_id', 'sequence'], unique=False)
    op.create_index('ix_captions_video_start', 'captions', ['video_id', 'start_ms'], unique=False)
    op.add_column('videos', sa.Column('progress', sa.Integer(), server_default='0', nullable=False))
    op.add_column('videos', sa.Column('stage', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'stage')
    op.drop_column('videos', 'progress')
    op.drop_index('ix_captions_video_start', table_name='captions')
    op.drop_index('ix_captions_video_sequence', table_name='captions')
    op.drop_index(op.f('ix_captions_video_id'), table_name='captions')
    op.drop_table('captions')
    # ### end Alembic commands ###
